- name: Remove User
  hosts: myserver
  tasks:
    - name: Kill All Processes
      shell: "killall -u {{username}}"
      ignore_errors: true
 
    - name: Wait for processes to terminate
      ansible.builtin.pause:
        seconds: 5

    - name: Remove User
      ansible.builtin.user:
        name: "{{username}}"
        state: absent
        remove: yes
